FROM python:3.8-slim

COPY requirements.txt .

RUN apt-get update \
    && pip3 install -r requirements.txt

COPY ./src/scripts /src/scripts
COPY ./src/utils /src/utils
COPY ./src/config.py /src/config.py
