version: '3.7'

services:
    mongo:
        image: mongo
        container_name: gpt2-twitter-mongo
        volumes:
            - ./mongo/data/db:/data/db
        env_file: .env
        ports:
            - 27017:27017
    # postgresserver:
    #     image: postgres:12.1-alpine
    #     volumes:
    #         - postgres_data:/var/lib/postgresql/data/
    #     environment:
    #         - POSTGRES_USER=${DB_USERNAME}
    #         - POSTGRES_PASSWORD=${DB_PASSWORD}
    #         - POSTGRES_DB=${DB_NAME}
    app:
        build:
            context: .
            dockerfile: Dockerfile.app
        container_name: gpt2-twitter-app
        command: uvicorn src.api.app:app --host 0.0.0.0 --port 8000
        ports:
            - 8000:8000
        env_file:
            - .env
    # tweet-script:
    #     build:
    #         context: .
    #         dockerfile: ./docker/Dockerfile.tweet
    #     container_name: post-twitter-script
    

# volumes:
#   postgres_data: