apiVersion: skaffold/v2beta16
kind: Config
metadata:
  name: gpt--twitter
build:
  artifacts:
  - image: aarongrainer/gpt2-tweet-app
    docker:
      dockerfile: Dockerfile.app
deploy:
  kubectl:
    manifests:
    - kubernetes/tweet-app.yaml
