apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: gpt2-post-tweet
  namespace: gpt2-twitter
  labels:
    app: gpt2-twitter
spec:
  schedule: "0 9 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: gpt2-post-tweet
              image: docker.io/aarongrainer/gpt2-post-tweet
              command:  ["python", "-m", "src.scripts.post_tweets"]
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
