apiVersion: v1
kind: Service
metadata:
  name: gpt2-tweet-app-service
spec:
  selector:
    app: gpt2-tweet-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpt2-tweet-app
  labels:
    app: gpt2-tweet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpt2-tweet-app
  template:
    metadata:
      labels:
        app: gpt2-tweet-app
    spec:
      containers:
        - name: gpt2-tweet-app
          image: aarongrainer/gpt2-tweet-app
          command: ["uvicorn", "src.api.app:app", "--host", "0.0.0.0", "--port", "8000"]
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
